config/routes.rb
Rails.application.routes.draw do
    root to: 'games#index'
    resources :games , only: [:index,:show, :create, :update, :destroy] do
      resources :words, only: [:index, :new, :update, :create]
    end


    get '/games/:id/timer', to: 'games#timer', as: 'timer'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :words, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :number, presence: true , numericality: true, :inclusion => 1..10
  validates :players, presence: true, numericality: true, :inclusion => 1..20
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :game
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :game
  validates :text, presence: true
  validates :text, uniqueness: {scope: [:game_id]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :update, :timer]
  before_action :set_words_left, only: [:show, :update]
  before_action :set_game_round_description, only: [:show]


  def index
    @games = Game.all.order(created_at: :desc)
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to new_game_word_path(@game)
    else
      render :index
    end
  end

  def show
    @check = ((@game.number * @game.players) > @game.words.count) ? 'Wartet! Mitspielerberiffe fehlen noch!' : ""
    respond_to do |format|
       format.html
       format.json { render json: { words_left: @words_left, round: @game_round_description, counter_a: @game.counter_a, counter_b: @game.counter_b, check: @check} }
    end
  end

  def update
    if game_params[:groupname] == 'c'
     @game.increment!(:round)
     @words = Word.where(game_id: params[:id])
     @words.update(status: true)
     redirect_to game_path(@game)
    else
      @game.update(groupname: game_params[:groupname])
      redirect_to game_words_path(@game)
    end
  end

  def timer
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :number, :id, :players, :groupname)
  end

  def set_words_left
    @words_left = Word.where(game_id: params[:id]).where(status: true)
  end

  def set_game_round_description
    case @game.round
     when 1
      @game_round_description = 'Erklären'
     when 2
      @game_round_description = 'Panthomime'
     when 3
      @game_round_description = 'Ein Wort'
     when 4
      @game_round_description = 'Geräusche'
     else
      @game_round_description = 'Spielende'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_game
  before_action :set_words , only: [:new, :create]
  before_action :set_description , only: [:index]


  def index
    @words = Word.where(game_id: params[:game_id]).where(status: true)
    @word = @words.sample
  end

  def new
    redirect_to game_path(@game) if (@game.number * @game.players) <= @words.count
    @word = Word.new
  end

  def create
    if word_params[:text].length > word_validation
     render :new
    elsif (@game.number * @game.players) <= @words.count
      redirect_to game_path(@game)
    else
      word_params[:text].each do |word|
        @word = Word.new(text: word, game_id: params[:game_id])
        @word.save
      end
      redirect_to game_path(@game)
    end
  end

  def update
    @word = Word.find(word_params[:id])
    @word.update(status: false)
    @game.groupname == 'a' ? @game.increment!(:counter_a) : @game.increment!(:counter_b)
    redirect_to game_words_path(@game)
  end


  private

  def word_validation
    i = 0
    word_params[:text].each do |word|
      @word = Word.new(text: word, game_id: params[:game_id])
      i += 1 if @word.valid?
    end
    i
  end

  def set_game
    @game = Game.find(params[:game_id])
  end

  def set_words
    @words = Word.where(game_id: params[:game_id])
  end

  def word_params
    params.require(:word).permit(:id, text:[])
  end

  def set_description
    case @game.round
     when 1
      @description = 'Erklären den folgenden Bergiff'
     when 2
      @description = 'Stelle den folgenden Bergiff panthomimisch dar'
     when 3
      @description = 'Du darfst den folgenden Begriff mit einem Wort beschreiben. Das Wort darf nicht mehr geändert werden'
     when 4
      @description = 'Beschreibe den Begriff mit (verschiedenen) Geräuschen'
     else
      @description = 'Spiel beendet'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="container ">
  <div class="row text-align">
    <div class="col-12">


      <div class="head">

        <h1>TOPFSPIEL</h1>
        <p> Zur allgemeinen Erheiterung des Gemüts </p>

      </div>

     <nav>
       <div class="nav nav-tabs" id="nav-tab" role="tablist">
         <a class="nav-item nav-link active " id="nav-old-tab" data-toggle="tab" href="#nav-old" role="tab" aria-controls="nav-old" aria-selected="false">Mitspielen</a>
         <a class="nav-item nav-link " id="nav-new-tab" data-toggle="tab" href="#nav-new" role="tab" aria-controls="nav-new" aria-selected="true">Spiel erstellen</a>
       </div>
     </nav>
     <div class="tab-content" id="nav-tabContent">

       <div class="tab-pane fade show active" id="nav-old" role="tabpanel" aria-labelledby="nav-old-tab">
        <div class="game">
          <p>Wenn ein Mitspieler schon ein neues Spiel erstellt hat, dann wähle es hier aus um mitzuspielen</p>
           <% unless @games.nil? %>
           <div class="game-item">
             <p><strong>Spielname</strong></p>
             <p><strong>erstellt am</strong></p>
           </div>
             <% @games.each do |game|%>
              <% if game.words.count < (game.number * game.players)%>
                <%= link_to new_game_word_path(game) do %>
                  <div class="game-item">
                    <p><%= game.name %></p>
                    <p><%= game.created_at.strftime("%d/%m/%Y")%></p>
                  </div>
                <% end %>
               <%else %>
                  <%= link_to game_path(game) do %>
                    <div class="game-item">
                      <p><%= game.name %></p>
                      <p><%= game.created_at.strftime("%d/%m/%Y")%></p>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
           <% end %>
        </div>
       </div>

       <div class="tab-pane fade " id="nav-new" role="tabpanel" aria-labelledby="nav-new-tab">
         <%= simple_form_for(@game) do |f| %>
           <%= f.input :name, label: 'Spielname' %>
           <%= f.input :players, label: 'Anzahl der Spieler'  %>
           <%= f.input :number, label: 'Anzahl der Begiffe pro Spieler'  %>
           <%= f.submit 'Spiel erstellen', class: 'button' %>
         <% end %>
       </div>
     </div>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">

  <div class="head">
    <h1>SPIELÜBERSICHT</h1>
    <p>Hallo Spieler   von <%= @game.name%>! Hier warten bis ihr an der Reihe seid</p>
  </div>



      <div data-controller="counter" >
        <div class="box ">
         <p><strong data-target="counter.check"></strong></p>
        </div>
        <div class="box">
          <p><strong>Aktuelle Spielrunde: </strong></p>
          <p><strong data-target="counter.round"><%= @game_round_description %></strong></p>
        </div>
        <div class="box">
          <p>Bergiffe noch im Topf</p>
          <% if  @words_left != nil %>
            <p ><strong data-target="counter.count"><%= @words_left.count %></strong><strong>/<%=(@game.number * @game.players)%></strong></p>
          <% else %>
            <p><strong>0</strong></p>
          <% end %>
        </div>

        <div class="box">
          <p>Punkte Gruppe A</p>
          <p><strong data-target="counter.count_a"><%= @game.counter_a %></strong></p>
        </div>
        <div class="box">
          <p>Punkte Gruppe B</p>
          <p><strong data-target="counter.count_b"><%= @game.counter_b %></strong></p>
        </div>


        <%= simple_form_for [@game] do |f| %>
            <%= f.input :groupname,  :input_html => { :value => "a"}, as: :hidden%>
            <%= f.submit 'Gruppe A spielt', class: 'button' %>
          <% end %>

         <%= simple_form_for [@game] do |f| %>
            <%= f.input :groupname , :input_html => { :value => "b"}, as: :hidden%>
            <%= f.submit 'Gruppe B spielt',class: 'button' %>
          <% end %>
      </div>



    <div class='next'>
      <%= link_to timer_path(@game) do %>
         <p>Zum Timer</p>
      <% end %>
    </div>



    <div class='next'>
      <%= link_to root_path(@game) do %>
         <p>Neues Spiel erstellen</p>
      <% end %>
    </div>



</div>

app/views/games/timer.html.erb
<div class="container ">

  <div class="head">
    <h1>TOPFSPIEL</h1>
    <p>Timer</p>
  </div>

  <div class="display timer">
    <h1 class="time-left">00:00</h1>
  </div>

 <div class="timer-box">
    <button data-time="60" class= 'button'> 1 Minute </button>
    <p>oder</p>
    <form name="customForm" id='custom_form'>
      <input class = 'input' type="text" name='seconds' placeholder='Gib Sekunden ein'>
    </form>
  </div>




  <div class='next'>
    <%= link_to game_path(@game) do %>
        <p>zurück zur Spielübersicht</p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="Topfspiel | Virtueller Topf zum ermöglichen des Topfspiels via Videotelefonie">
    <meta property="og:title" content="Topfspiel" />
    <meta property="og:description" content="Virtueller Topf zum ermöglichen des Topfspiels via Videotelefonie" />

    <%= favicon_link_tag asset_path('favicon.svg') %>
    <title>Topfspiel | Virtueller Topf </title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/words/index.html.erb
<div class="container ">

  <div class="head">
    <h1>TOPFSPIEL</h1>
    <p><%=@description%></p>
  </div>


  <% if @word != nil%>
    <div class="card">
      <h2><%= @word.text %></h2>
    </div>
    <% else %>
    <p>es sind keine Wörter mehr im Topf</p>
  <% end %>


  <% if @word != nil%>
      <%= simple_form_for [@game, @word] do |f| %>
        <%= f.input :id , value: @word.id, as: :hidden %>
        <%= f.submit 'gelöst' , class: 'button solved'%>
      <% end %>
    <div class='next'>
      <%= link_to game_path(@game) do %>
          <p>nächster Spieler </p>
      <% end %>
    </div>
  <% else %>
    <%= simple_form_for [@game] do |f| %>
      <%= f.input :groupname , :input_html => { :value => "c"}, as: :hidden%>
      <%= f.submit 'Neue Runde',class: 'button' %>
    <% end %>
  <% end %>
 </div>

app/views/words/new.html.erb
<div class="container">

  <div class="head">
    <h1>NEUER BEGRIFF</h1>
    <p>Hier <strong><%= @game.number %></strong> Begriffe, Personen, Bla Bla eingeben  </p>
  </div>

  <%= simple_form_for [@game, @word] do |f| %>
  <% @game.number.times do %>
    <%= f.input :text, label: 'Hirnpfurz', as: :text, input_html: { multiple: true } %>
    <% end %>
    <%= f.submit 'Rein in den Topf', class: 'button' %>
  <% end %>

  <div class='next'>
    <%= link_to game_path(@game) do %>
        <p>Direkt zur Spielübersicht</p>
    <% end %>
  </div>

</div>